version: '2'
services:
    mariadb:
        container_name: mariadb
        hostname: azkaban-webserver
        image: mariadb:10
        #restart: always
        ports:
            - 3306
        environment:
            - MYSQL_USER=azkaban
            - MYSQL_PASSWORD=azkaban
            - MYSQL_DATABASE=azkaban
            - MYSQL_ROOT_PASSWORD=wootwoot
        volumes:
            - mariadbvolume:/var/lib/mysql
    executor:
        container_name: azkaban-executor
        hostname: azkaban-executor
        image: cogfor/azkaban-executor
        #restart: always
        depends_on:
            - mariadb

    webserver:
        container_name: azkaban-webserver
        hostname: azkaban-webserver
        image: cogfor/azkaban-webserver
        #restart: always
        ports:
            - 8443:8443
        depends_on:
            - executor
            - mariadb

volumes:
    mariadbvolume:
