# VERSION 1.0
# AUTHOR: Matthieu "Puckel_" Roisil
# DOCKER HUB: https://hub.docker.com/u/puckel/
# DESCRIPTION: Simple Debian image for azkaban-executor based on official java:8
# BUILD: docker build --rm -t puckel/azkaban-executor .
# SOURCE: https://github.com/puckel/docker-azkaban

FROM java:8
MAINTAINER Puckel_

# Never prompts the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND noninteractive
ENV TERM linux
# Work around initramfs-tools running on kernel 'upgrade': <http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=594189>
ENV INITRD No

ENV AZK_VERSION 3.6.0
#ENV MYSQL_JDBC_VERSION 5.1.40

WORKDIR /root

COPY bin/azkaban-exec-server-$AZK_VERSION.tar.gz /root/azkaban-exec-server-$AZK_VERSION.tar.gz

RUN apt-get update -yqq \
    && apt-get install -yqq \
    curl \
    awscli \
	&& tar xfz azkaban-exec-server-$AZK_VERSION.tar.gz \ 
    #&& curl -sLk https://s3-eu-west-1.amazonaws.com/ci-rtlambda/dist/azkaban/azkaban-exec-server-$AZK_VERSION.tar.gz | tar xz \
    #&& curl -sLk http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-$MYSQL_JDBC_VERSION.tar.gz | tar xz \
    #&& mv mysql-connector-java-$MYSQL_JDBC_VERSION/mysql-connector-java-$MYSQL_JDBC_VERSION-bin.jar azkaban-exec-server-$AZK_VERSION/lib/ \
    #&& rm -rf mysql-connector-java-$MYSQL_JDBC_VERSION \
    # Work around to run container as a daemon
    && sed -i "s/&//" azkaban-exec-server-$AZK_VERSION/bin/azkaban-executor-start.sh \
    && apt-get clean \
    && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/* \
    /usr/share/man \
    /usr/share/doc \
    /usr/share/doc-base

ADD conf/azkaban.properties azkaban-exec-server-$AZK_VERSION/conf/azkaban.properties

# Azkaban executor port
EXPOSE 12321

# Define default workdir
WORKDIR /root/azkaban-exec-server-$AZK_VERSION

CMD ["bin/azkaban-executor-start.sh"]
